# If error:
# collect2: error: ld returned 1 exit status
# *** [.pioenvs/garage-door-pico/firmware.elf] Error 1

# Then try removing "rm -rf /data/cache/platformio/platforms/raspberrypi/" from HASSOS ESPHOME container.

# If still not working, pick an older build, like https://github.com/maxgerhardt/platform-raspberrypi.git#3821cc1

# History of branches:
#Commits on Sep 23, 2024 (works)
#3821cc132c2707a0cfdb44984ccbfc22649dc3f9

#Commits on Sep 27, 2024 (broken)
#2a8c40e25c1be1c245f269c856a5111a4c47b435

#Commits on Sep 28, 2024 (broken)
#8853c08f7964cfc2d3ba20e303213c5f8faeae71

#Commits on Sep 29, 2024 (broken)
#a7eddaaf010b973987b013d3f7380891e9afd449

#Commits on Sep 30, 2024 (broken)
#1177f9c9029080d1a1f6ffa27028580c7147873f

#Commits on Oct 1, 2024 (broken)
#088a074ba98e091f9abc48db91b99bedf908332b

#Commits on Oct 6, 2024 (broken)
#5b72058658ebaf98045755662bc8b28479bd288b

#Commits on Oct 12, 2024 (broken)
#2d445020acf8b792768a5fa5ba1870ac9607c11c

substitutions:
  name: multisensor-01
  friendly_name: Multi-Sensor 01 Up

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key02

# Enable over-the-air updates.
ota:
  platform: esphome
  password: !secret ota_password02

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

# Connect to WiFi.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_hotspot_password

# Enable Web server. Not yet supported on Pico.
#web_server:
#  port: 80

# LED on
output:
  - platform: gpio
    pin:
      number: 32  # 25 for Pico (non-W)
      mode: output
    id: LED

interval:
  - interval: 500ms
    then:
      - output.turn_on: LED
#      - delay: 250ms
#      - output.turn_off: LED

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# https://microcontrollerslab.com/?s=BME680
# https://community.home-assistant.io/t/esphome-bme680-coding-problem-communication-with-bme680-failed/159225
# https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME680-on-ESPHome-using-Bosch-s-BSEC-library/td-p/13210/page/3
# https://community.home-assistant.io/t/bme680-gas-resistance-values/140719

# i2c
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bme_680

# bme680 sensor
sensor:
  - platform: bme680
    i2c_id: bme_680
    address: 0x77
    temperature:
      name: BME680 Temperature
      unit_of_measurement: '°C'
      oversampling: 16x
      accuracy_decimals: 1
      filters:
        - offset: '-0.5'
      icon: mdi:thermometer
    pressure:
      name: BME680 Pressure
      unit_of_measurement: 'hPa'
      accuracy_decimals: 1
      filters:
        - offset: '27.2'
      icon: mdi:gauge
    humidity:
      name: BME680 Humidity
      unit_of_measurement: '%'
      accuracy_decimals: 1
      icon: mdi:water-percent
      id: hum
    gas_resistance:
      name: BME680 Gas Resistance
      accuracy_decimals: 1
      icon: mdi:gas-cylinder
      id: g_res
# comp_gas = log(R_gas[ohm]) + 0.04 log(Ohm)/%rh * hum[%rh]    
  - platform: template
    name: BME680 IAQ
    unit_of_measurement: IAQ
    accuracy_decimals: 1
    icon: mdi:gauge
    id: IAQ
    lambda: 'return log(id(g_res).state) + 0.04 *  id(hum).state;'

# Indoor Air Quality (IAQ) Index Classification:
# 000 .. 050 Excellent
# 051 .. 100 Good
# 101 .. 150 Lightly polluted
# 151 .. 200 Moderately polluted
# 201 .. 250 Heavily polluted
# 251 .. 350 Severely polluted
# 351 .. 500 Extremely polluted
