substitutions:
  devicename: "multisensor-01"
  upper_devicename: "Multi-Sensor 01 Up"

esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key02

ota:
  password: !secret ota_password02

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${upper_devicename}"
    password: !secret wifi_hotspot_password

# Enable Web server. Not yet supported on Pico.
#web_server:
#  port: 80

# LED on
output:
  - platform: gpio
    pin:
      number: 32  # 25 for Pico (non-W)
      mode: output
    id: LED

interval:
  - interval: 500ms
    then:
      - output.turn_on: LED
#      - delay: 250ms
#      - output.turn_off: LED

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# https://microcontrollerslab.com/?s=BME680
# https://community.home-assistant.io/t/esphome-bme680-coding-problem-communication-with-bme680-failed/159225
# https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME680-on-ESPHome-using-Bosch-s-BSEC-library/td-p/13210/page/3
# https://community.home-assistant.io/t/bme680-gas-resistance-values/140719

# i2c
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bme_680

# bme680 sensor
sensor:
  - platform: bme680
    i2c_id: bme_680
    address: 0x77
    temperature:
      name: "BME680 Temperature"
      unit_of_measurement: '°C'
      oversampling: 16x
      accuracy_decimals: 1
      filters:
        - offset: '-0.5'
      icon: mdi:thermometer
    pressure:
      name: "BME680 Pressure"
      unit_of_measurement: 'hPa'
      accuracy_decimals: 1
      filters:
        - offset: '27.2'
      icon: mdi:gauge
    humidity:
      name: "BME680 Humidity"
      unit_of_measurement: '%'
      accuracy_decimals: 1
      icon: mdi:water-percent
      id: hum
    gas_resistance:
      name: "BME680 Gas Resistance"
      accuracy_decimals: 1
      icon: mdi:gas-cylinder
      id: g_res
# comp_gas = log(R_gas[ohm]) + 0.04 log(Ohm)/%rh * hum[%rh]    
  - platform: template
    name: "BME680 IAQ"
    unit_of_measurement: IAQ
    accuracy_decimals: 1
    icon: mdi:gauge
    id: IAQ
    lambda: 'return log(id(g_res).state) + 0.04 *  id(hum).state;'

# Indoor Air Quality (IAQ) Index Classification:
# 000 .. 050 Excellent
# 051 .. 100 Good
# 101 .. 150 Lightly polluted
# 151 .. 200 Moderately polluted
# 201 .. 250 Heavily polluted
# 251 .. 350 Severely polluted
# 351 .. 500 Extremely polluted
